-- 1638496080-LoadTables.sql

-- Autor: Olimpo Bonilla Ramírez.
-- Objetivo: Carga de datos en tablas existentes de Base de Datos.
-- Fecha: 2021-12-02.
-- Comentarios: Aquí se crean los objetos de Base de Datos (Tablas, vistas, SP, etc) asignados a un esquema de Base de Datos o bien asignados al esquema por default de Base de Datos.

-- 1. Catálogo de cuentas de usuario.
-------------------------------------
INSERT INTO [dbo].[mtUsers] ([first_name], [last_name], [username], [passwordhash], [email], [number_phone], [adress], [postal_code], [country_code],
                             [federal_entity_code], [municipality_code], [neighborhood_code], [number_of_attemps],
                             [status_account], [role_id], [issystemrow], [isdeleted], [creationdate], [account_id_creationdate], 
                             [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
VALUES ('ADMINISTRADOR', 'DEL SISTEMA', 'root', 'SBNJTRN+FjG7owHVrKtue7eqdM4RhdRWVl71HXN2d7I=', 'admin@mail.com', '5512345678', 'S/D', 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       ('INVITADO', 'DEL SISTEMA', 'userguest', '6L2/s9KMKzIKq9+wG/EZZi/KIgDbLrnh76xsp/daoBY=', 'userguest@mail.com', '5512345678', 'S/D', 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, GETUTCDATE(), 0, null, null, null, null);

-- 2. Catálogo de cuentas de universo de países del mundo.
----------------------------------------------------------
SET IDENTITY_INSERT [dbo].[mtCountries] ON;
INSERT INTO [dbo].[mtCountries] ([country_code], [iso], [name_country], [nicename], [iso3], [numcode], [phonecode],
                                 [issystemrow], [isdeleted], [creationdate], [account_id_creationdate], [updatedate],
                                 [account_id_updatedate], [deletedate], [account_id_deletedate])
     VALUES (0, '', 'NO DATA', 'NO DATA', 'NDT', 0, 0, 0, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
		        (1, 'AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 93, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (2, 'AL', 'ALBANIA', 'Albania', 'ALB', 8, 355, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (3, 'DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 213, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (4, 'AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 1684, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (5, 'AD', 'ANDORRA', 'Andorra', 'AND', 20, 376, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (6, 'AO', 'ANGOLA', 'Angola', 'AGO', 24, 244, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (7, 'AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 1264, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (8, 'AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (9, 'AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 1268, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (10, 'AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 54, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (11, 'AM', 'ARMENIA', 'Armenia', 'ARM', 51, 374, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (12, 'AW', 'ARUBA', 'Aruba', 'ABW', 533, 297, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (13, 'AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 61, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (14, 'AT', 'AUSTRIA', 'Austria', 'AUT', 40, 43, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (15, 'AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 994, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (16, 'BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 1242, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (17, 'BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 973, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (18, 'BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 880, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (19, 'BB', 'BARBADOS', 'Barbados', 'BRB', 52, 1246, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (20, 'BY', 'BELARUS', 'Belarus', 'BLR', 112, 375, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (21, 'BE', 'BELGIUM', 'Belgium', 'BEL', 56, 32, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (22, 'BZ', 'BELIZE', 'Belize', 'BLZ', 84, 501, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (23, 'BJ', 'BENIN', 'Benin', 'BEN', 204, 229, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (24, 'BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 1441, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (25, 'BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 975, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (26, 'BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 591, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (27, 'BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 387, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (28, 'BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 267, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (29, 'BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (30, 'BR', 'BRAZIL', 'Brazil', 'BRA', 76, 55, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (31, 'IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL, 246, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (32, 'BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 673, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (33, 'BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 359, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (34, 'BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 226, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (35, 'BI', 'BURUNDI', 'Burundi', 'BDI', 108, 257, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (36, 'KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 855, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (37, 'CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 237, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (38, 'CA', 'CANADA', 'Canada', 'CAN', 124, 1, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (39, 'CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 238, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (40, 'KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 1345, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (41, 'CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 236, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (42, 'TD', 'CHAD', 'Chad', 'TCD', 148, 235, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (43, 'CL', 'CHILE', 'Chile', 'CHL', 152, 56, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (44, 'CN', 'CHINA', 'China', 'CHN', 156, 86, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (45, 'CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, 61, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (46, 'CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 672, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (47, 'CO', 'COLOMBIA', 'Colombia', 'COL', 170, 57, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (48, 'KM', 'COMOROS', 'Comoros', 'COM', 174, 269, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (49, 'CG', 'CONGO', 'Congo', 'COG', 178, 242, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (50, 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 242, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (51, 'CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 682, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (52, 'CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 506, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (53, 'CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384, 225, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (54, 'HR', 'CROATIA', 'Croatia', 'HRV', 191, 385, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (55, 'CU', 'CUBA', 'Cuba', 'CUB', 192, 53, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (56, 'CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 357, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (57, 'CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203, 420, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (58, 'DK', 'DENMARK', 'Denmark', 'DNK', 208, 45, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (59, 'DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 253, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (60, 'DM', 'DOMINICA', 'Dominica', 'DMA', 212, 1767, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (61, 'DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 1809, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (62, 'EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 593, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (63, 'EG', 'EGYPT', 'Egypt', 'EGY', 818, 20, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (64, 'SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 503, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (65, 'GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 240, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (66, 'ER', 'ERITREA', 'Eritrea', 'ERI', 232, 291, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (67, 'EE', 'ESTONIA', 'Estonia', 'EST', 233, 372, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (68, 'ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 251, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (69, 'FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 500, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (70, 'FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 298, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (71, 'FJ', 'FIJI', 'Fiji', 'FJI', 242, 679, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (72, 'FI', 'FINLAND', 'Finland', 'FIN', 246, 358, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (73, 'FR', 'FRANCE', 'France', 'FRA', 250, 33, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (74, 'GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 594, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (75, 'PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 689, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (76, 'TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (77, 'GA', 'GABON', 'Gabon', 'GAB', 266, 241, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (78, 'GM', 'GAMBIA', 'Gambia', 'GMB', 270, 220, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (79, 'GE', 'GEORGIA', 'Georgia', 'GEO', 268, 995, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (80, 'DE', 'GERMANY', 'Germany', 'DEU', 276, 49, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (81, 'GH', 'GHANA', 'Ghana', 'GHA', 288, 233, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (82, 'GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 350, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (83, 'GR', 'GREECE', 'Greece', 'GRC', 300, 30, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (84, 'GL', 'GREENLAND', 'Greenland', 'GRL', 304, 299, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (85, 'GD', 'GRENADA', 'Grenada', 'GRD', 308, 1473, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (86, 'GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 590, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (87, 'GU', 'GUAM', 'Guam', 'GUM', 316, 1671, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (88, 'GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 502, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (89, 'GN', 'GUINEA', 'Guinea', 'GIN', 324, 224, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (90, 'GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 245, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (91, 'GY', 'GUYANA', 'Guyana', 'GUY', 328, 592, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (92, 'HT', 'HAITI', 'Haiti', 'HTI', 332, 509, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (93, 'HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (94, 'VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 39, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (95, 'HN', 'HONDURAS', 'Honduras', 'HND', 340, 504, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (96, 'HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 852, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (97, 'HU', 'HUNGARY', 'Hungary', 'HUN', 348, 36, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (98, 'IS', 'ICELAND', 'Iceland', 'ISL', 352, 354, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (99, 'IN', 'INDIA', 'India', 'IND', 356, 91, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (100, 'ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 62, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (101, 'IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 98, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (102, 'IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 964, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (103, 'IE', 'IRELAND', 'Ireland', 'IRL', 372, 353, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (104, 'IL', 'ISRAEL', 'Israel', 'ISR', 376, 972, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (105, 'IT', 'ITALY', 'Italy', 'ITA', 380, 39, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (106, 'JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 1876, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (107, 'JP', 'JAPAN', 'Japan', 'JPN', 392, 81, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (108, 'JO', 'JORDAN', 'Jordan', 'JOR', 400, 962, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (109, 'KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 7, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (110, 'KE', 'KENYA', 'Kenya', 'KEN', 404, 254, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (111, 'KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 686, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (112, 'KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408, 850, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (113, 'KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 82, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (114, 'KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 965, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (115, 'KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 996, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (116, 'LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418, 856, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (117, 'LV', 'LATVIA', 'Latvia', 'LVA', 428, 371, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (118, 'LB', 'LEBANON', 'Lebanon', 'LBN', 422, 961, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (119, 'LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 266, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (120, 'LR', 'LIBERIA', 'Liberia', 'LBR', 430, 231, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (121, 'LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 218, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (122, 'LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 423, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (123, 'LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 370, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (124, 'LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 352, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (125, 'MO', 'MACAO', 'Macao', 'MAC', 446, 853, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (126, 'MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 389, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (127, 'MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 261, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (128, 'MW', 'MALAWI', 'Malawi', 'MWI', 454, 265, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (129, 'MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 60, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (130, 'MV', 'MALDIVES', 'Maldives', 'MDV', 462, 960, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (131, 'ML', 'MALI', 'Mali', 'MLI', 466, 223, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (132, 'MT', 'MALTA', 'Malta', 'MLT', 470, 356, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (133, 'MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 692, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (134, 'MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 596, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (135, 'MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 222, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (136, 'MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 230, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (137, 'YT', 'MAYOTTE', 'Mayotte', NULL, NULL, 269, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (138, 'MX', 'MEXICO', 'Mexico', 'MEX', 484, 52, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (139, 'FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 691, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (140, 'MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 373, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (141, 'MC', 'MONACO', 'Monaco', 'MCO', 492, 377, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (142, 'MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 976, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (143, 'MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 1664, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (144, 'MA', 'MOROCCO', 'Morocco', 'MAR', 504, 212, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (145, 'MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 258, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (146, 'MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 95, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (147, 'NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 264, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (148, 'NR', 'NAURU', 'Nauru', 'NRU', 520, 674, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (149, 'NP', 'NEPAL', 'Nepal', 'NPL', 524, 977, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (150, 'NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 31, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (151, 'AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 599, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (152, 'NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 687, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (153, 'NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 64, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (154, 'NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 505, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (155, 'NE', 'NIGER', 'Niger', 'NER', 562, 227, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (156, 'NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 234, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (157, 'NU', 'NIUE', 'Niue', 'NIU', 570, 683, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (158, 'NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 672, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (159, 'MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 1670, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (160, 'NO', 'NORWAY', 'Norway', 'NOR', 578, 47, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (161, 'OM', 'OMAN', 'Oman', 'OMN', 512, 968, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (162, 'PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 92, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (163, 'PW', 'PALAU', 'Palau', 'PLW', 585, 680, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (164, 'PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 970, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (165, 'PA', 'PANAMA', 'Panama', 'PAN', 591, 507, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (166, 'PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 675, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (167, 'PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 595, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (168, 'PE', 'PERU', 'Peru', 'PER', 604, 51, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (169, 'PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 63, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (170, 'PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (171, 'PL', 'POLAND', 'Poland', 'POL', 616, 48, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (172, 'PT', 'PORTUGAL', 'Portugal', 'PRT', 620, 351, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (173, 'PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 1787, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (174, 'QA', 'QATAR', 'Qatar', 'QAT', 634, 974, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (175, 'RE', 'REUNION', 'Reunion', 'REU', 638, 262, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (176, 'RO', 'ROMANIA', 'Romania', 'ROM', 642, 40, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (177, 'RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 70, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (178, 'RW', 'RWANDA', 'Rwanda', 'RWA', 646, 250, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (179, 'SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 290, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (180, 'KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 1869, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (181, 'LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 1758, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (182, 'PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 508, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (183, 'VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (184, 'WS', 'SAMOA', 'Samoa', 'WSM', 882, 684, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (185, 'SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 378, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (186, 'ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 239, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (187, 'SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 966, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (188, 'SN', 'SENEGAL', 'Senegal', 'SEN', 686, 221, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (189, 'CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL, 381, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (190, 'SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 248, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (191, 'SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 232, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (192, 'SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 65, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (193, 'SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 421, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (194, 'SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 386, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (195, 'SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 677, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (196, 'SO', 'SOMALIA', 'Somalia', 'SOM', 706, 252, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (197, 'ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 27, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (198, 'GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 0, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (199, 'ES', 'SPAIN', 'Spain', 'ESP', 724, 34, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (200, 'LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 94, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (201, 'SD', 'SUDAN', 'Sudan', 'SDN', 736, 249, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (202, 'SR', 'SURINAME', 'Suriname', 'SUR', 740, 597, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (203, 'SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 47, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (204, 'SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 268, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (205, 'SE', 'SWEDEN', 'Sweden', 'SWE', 752, 46, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (206, 'CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 41, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (207, 'SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 963, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (208, 'TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 886, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (209, 'TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 992, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (210, 'TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 255, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (211, 'TH', 'THAILAND', 'Thailand', 'THA', 764, 66, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (212, 'TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, 670, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (213, 'TG', 'TOGO', 'Togo', 'TGO', 768, 228, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (214, 'TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 690, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (215, 'TO', 'TONGA', 'Tonga', 'TON', 776, 676, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (216, 'TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 1868, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (217, 'TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 216, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (218, 'TR', 'TURKEY', 'Turkey', 'TUR', 792, 90, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (219, 'TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 7370, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (220, 'TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 1649, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (221, 'TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 688, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (222, 'UG', 'UGANDA', 'Uganda', 'UGA', 800, 256, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (223, 'UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 380, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (224, 'AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 971, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (225, 'GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 44, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (226, 'US', 'UNITED STATES', 'United States', 'USA', 840, 1, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (227, 'UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL, 1, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (228, 'UY', 'URUGUAY', 'Uruguay', 'URY', 858, 598, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (229, 'UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 998, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (230, 'VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 678, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (231, 'VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 58, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (232, 'VN', 'VIET NAM', 'Viet Nam', 'VNM', 704, 84, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (233, 'VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 1284, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (234, 'VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 1340, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (235, 'WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 681, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (236, 'EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 212, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (237, 'YE', 'YEMEN', 'Yemen', 'YEM', 887, 967, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (238, 'ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 260, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL),
            (239, 'ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 263, 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[mtCountries] OFF;
GO

-- 3. Catálogo de cuentas de universo de países del mundo (detalle).
--------------------------------------------------------------------
SET IDENTITY_INSERT [dbo].[mtCountriesDetail] ON;
INSERT INTO [dbo].[mtCountriesDetail] ([postalcode_id], [country_code], [federal_entity_code], [federal_entity_name], [municipality_code], [municipality_name], [city_name],
                                       [zone_name], [postal_code], [township_id], [township_name], [township_type_id], [township_type_name],
                                       [issystemrow], [isdeleted], [creationdate], [account_id_creationdate], [updatedate],
                                       [account_id_updatedate], [deletedate], [account_id_deletedate])
     VALUES (0, 0, 0, 'NO DATA', 0, 'NO DATA', 'NO DATA', 'N/A', 0, 0, 'NO DATA', 0, 'NO DATA', 1, 0, GETUTCDATE(), 0, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[mtCountriesDetail] OFF;

-- NOTA: Cargar la información del detalle de un país del mundo en especifico.
------------------------------------------------------------------------------

-- 4. Catálogo de espacio de nombre de código.
----------------------------------------------
INSERT INTO [dbo].[mtCodeNamespaces] ([name], [list], [issystemrow], [isdeleted], [creationdate], [account_id_creationdate], [updatedate], 
                                      [account_id_updatedate], [deletedate], [account_id_deletedate])
VALUES ('status_account', 'mtUser', 1, 0, GETUTCDATE(), 0, null, null, null, null),
       ('role_id', 'mtUser', 1, 0, GETUTCDATE(), 0, null, null, null, null),
       ('menusys_id', 'system', 1, 0, GETUTCDATE(), 0, null, null, null, null),
       ('movement_status', 'mtItemMovement', 0, 0, GETUTCDATE(), 0, null, null, null, null),
       ('departament_id', 'mtArticles', 0, 0, GETUTCDATE(), 0, null, null, null, null),
       ('producttype_id', 'mtArticles', 0, 0, GETUTCDATE(), 0, null, null, null, null),
       ('brand_id', 'mtArticles', 0, 0, GETUTCDATE(), 0, null, null, null, null),
       ('status_order', 'mtOrders', 0, 0, GETUTCDATE(), 0, null, null, null, null),
       ('type_order', 'mtOrders', 0, 0, GETUTCDATE(), 0, null, null, null, null);

-- 5. Catálogo de valores de nombre de código.
-- Fuente: https://blog.sqlauthority.com/2010/03/22/sql-server-enumerations-in-relational-database-best-practice/
----------------------------------------------
INSERT INTO [dbo].[mtCodeValues] ([value_id], [codenamespaceid], [description], [isroot], [parentid], [orderby],
                                  [issystemrow], [isdeleted], [creationdate], [account_id_creationdate], [updatedate],
                                  [account_id_updatedate], [deletedate], [account_id_deletedate])
VALUES (1, 1, 'Activo', 0, 0, 1, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 1, 'Bloqueado', 0, 0, 2, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (3, 1, 'Eliminado', 0, 0, 3, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (4, 1, 'Sin permisos', 0, 0, 4, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 2, 'Administrador', 0, 0, 1, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 2, 'Invitado', 0, 0, 2, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 3, 'Administración', 1, 0, 1, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 3, 'Catálogos', 1, 0, 2, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (3, 3, 'Procesos', 1, 0, 3, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (4, 3, 'Reportes', 1, 0, 4, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (5, 3, 'Perfiles de usuario', 1, 1, 5, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (6, 3, 'Permisos de usuario', 1, 1, 6, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (7, 3, 'Cuentas de usuario', 1, 1, 7, 1, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 4, 'Alta en Centro de Distribución', 0, 0, 1, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 4, 'Envío a sucursal', 0, 0, 2, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (3, 4, 'Baja de Centro de Distribución', 0, 0, 3, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (4, 4, 'Baja de sucursal', 0, 0, 4, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (5, 4, 'Venta en Centro de Distribución', 0, 0, 5, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (6, 4, 'Compra en Centro de Distribución', 0, 0, 6, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (7, 4, 'Venta en Sucursal', 0, 0, 7, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (8, 4, 'Compra en Sucursal', 0, 0, 8, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (9, 4, 'Devolución de Sucursal a Centro de Distribución', 0, 0, 9, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (10, 4, 'Devolución del cliente', 0, 0, 10, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 5, 'Abarrotes', 1, 0, 1, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 5, 'Lácteos', 1, 0, 2, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (3, 5, 'Frutas y Verduras', 1, 0, 3, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (4, 5, 'Carnes, Pescados y Mariscos', 1, 0, 4, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (5, 5, 'Salchichonería', 1, 0, 5, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (6, 5, 'Panadería y Tortillería', 1, 0, 6, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (7, 5, 'Bebidas y Licores', 1, 0, 7, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (8, 5, 'Congelados', 1, 0, 8, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (9, 5, 'Limpieza para el Hogar', 1, 0, 9, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (10, 5, 'Detergente y Suavizante', 1, 0, 10, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (11, 5, 'Mascotas', 1, 0, 11, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (12, 5, 'Bebés', 1, 0, 12, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (13, 5, 'Farmacia', 1, 0, 13, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (14, 5, 'Higiene y Belleza', 1, 0, 14, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (15, 5, 'Electrónica', 1, 0, 15, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (16, 5, 'Artículos para el Hogar y autos', 1, 0, 16, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (17, 5, 'Ropa y Zapatería', 1, 0, 17, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (18, 5, 'Juguetería y Deportes', 1, 0, 18, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (19, 6, 'Café, Té y Sustitutos', 0, 1, 19, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (20, 6, 'Pan y Tortillas Empacados', 0, 1, 20, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (21, 6, 'Cereales y Barras', 0, 1, 21, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (22, 6, 'Galletas', 0, 1, 22, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (23, 6, 'Enlatados y Conservas', 0, 1, 23, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (24, 6, 'Leche', 0, 1, 24, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (25, 6, 'Azúcar y Postres', 0, 1, 25, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (26, 6, 'Mermeladas y Miel', 0, 1, 26, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (27, 6, 'Dulces y Chocolates', 0, 1, 27, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (28, 6, 'Botanas y Fruta Seca', 0, 1, 28, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (29, 6, 'Salsas, Aderezos y Vinagre', 0, 1, 29, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (30, 6, 'Pastas', 0, 1, 30, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (31, 6, 'Harina y Repostería', 0, 1, 31, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (32, 6, 'Saborizantes y Jarabes', 0, 1, 32, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (33, 6, 'Arroz, Frijol y Semillas', 0, 1, 33, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (34, 6, 'Especias y Sazonadores', 0, 1, 34, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (35, 6, 'Alimentos Instantáneos', 0, 1, 35, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (36, 6, 'Comida Oriental', 0, 1, 36, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (37, 6, 'Alimentos Saludables', 0, 1, 37, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (38, 6, 'Aceites de Cocina', 0, 1, 38, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (39, 6, 'Leche', 0, 2, 39, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (40, 6, 'Yogurt', 0, 2, 40, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (41, 6, 'Gelatinas y Postres', 0, 2, 41, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (42, 6, 'Mantequilla y margarina', 0, 2, 42, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (43, 6, 'Huevo', 0, 2, 43, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (44, 6, 'Crema', 0, 2, 44, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (45, 6, 'Quesos', 0, 2, 45, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (46, 6, 'Alimento Líquido', 0, 2, 46, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (47, 6, 'Quesos Gourmet', 0, 2, 47, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (48, 6, 'Frutas', 0, 3, 48, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (49, 6, 'Verduras', 0, 3, 49, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (50, 6, 'Orgánicos y Superfoods', 0, 3, 50, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (51, 6, 'Pollo y Pavo', 0, 4, 51, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (52, 6, 'Cerdo', 0, 4, 52, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (53, 6, 'Pescados y Mariscos', 0, 4, 53, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (54, 6, 'Res', 0, 4, 54, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (55, 6, 'Sushi', 0, 4, 55, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (56, 6, 'Carnes frías', 0, 5, 56, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (57, 6, 'Artículos a granel', 0, 5, 57, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (58, 6, 'Quesos', 0, 5, 58, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (59, 6, 'Empacados', 0, 5, 59, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (60, 6, 'Pan Salado', 0, 6, 60, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (61, 6, 'Tortillería', 0, 6, 61, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (62, 6, 'Pan Dulce', 0, 6, 62, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (63, 6, 'Pasteles, Panqués y Postres', 0, 6, 63, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (64, 6, 'Pan para Hornear y Pasta Hojaldre', 0, 6, 64, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (65, 6, 'Pan de Temporada', 0, 6, 65, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (66, 6, 'Especializados', 0, 6, 66, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (67, 6, 'Comida y Snacks', 0, 6, 67, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (68, 6, 'Cervezas', 0, 7, 68, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (69, 6, 'Coolers', 0, 7, 69, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (70, 6, 'Licores Digestivos', 0, 7, 70, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (71, 6, 'Licores', 0, 7, 71, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (72, 6, 'Vinos', 0, 7, 72, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (73, 6, 'Agua', 0, 7, 73, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (74, 6, 'Energizantes e Hidratantes', 0, 7, 74, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (75, 6, 'Café y Té Preparado', 0, 7, 75, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (76, 6, 'Jugos y Néctares', 0, 7, 76, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (77, 6, 'Polvos y Jarabes', 0, 7, 77, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (78, 6, 'Refrescos', 0, 7, 78, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (79, 6, 'Comida Fácil', 0, 8, 79, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (80, 6, 'Frutas y Verduras Congeladas', 0, 8, 80, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (81, 6, 'Hielo', 0, 8, 81, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (82, 6, 'Postres Congelados', 0, 8, 82, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (83, 6, 'Accesorios para Limpieza', 0, 9, 83, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (84, 6, 'Desechables', 0, 9, 84, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (85, 6, 'Aromatizantes', 0, 9, 85, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (86, 6, 'Lavatrastes y lavavajillas', 0, 9, 86, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (87, 6, 'Limpieza del hogar', 0, 9, 87, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (88, 6, 'Papel higiénico', 0, 9, 88, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (89, 6, 'Desinfectantes', 0, 9, 89, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (90, 6, 'Insecticidas y Trampas', 0, 9, 90, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (91, 6, 'Almidón y Colorantes para Ropa', 0, 10, 91, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (92, 6, 'Blanqueadores', 0, 10, 92, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (93, 6, 'Detergente', 0, 10, 93, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (94, 6, 'Jabón de Lavandería', 0, 10, 94, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (95, 6, 'Quitamanchas para Ropa', 0, 10, 95, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (96, 6, 'Suavizantes', 0, 10, 96, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (97, 6, 'Alimento para Perros', 0, 11, 97, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (98, 6, 'Arenas y Accesorios Gatos', 0, 11, 98, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (99, 6, 'Alimento y accesorios otras mascotas', 0, 11, 99, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (100, 6, 'Accesorios e Higiene Perros', 0, 11, 100, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (101, 6, 'Alimento para Gatos', 0, 11, 101, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (102, 6, 'Pañales y toallitas húmedas para bebé', 0, 12, 102, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (103, 6, 'Juguetes para bebé y estimulación temprana', 0, 12, 103, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (104, 6, 'Higiene del bebé', 0, 12, 104, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (105, 6, 'Fórmula láctea', 0, 12, 105, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (106, 6, 'Leche de Crecimiento', 0, 12, 106, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (107, 6, 'Comida para bebé y lactancia', 0, 12, 107, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (108, 6, 'Artículos para fiesta', 0, 12, 108, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (109, 6, 'Ropa para bebé', 0, 12, 109, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (110, 6, 'Cunas, carriolas y accesorios', 0, 12, 110, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (111, 6, 'Vitaminas y Suplementos', 0, 13, 111, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (112, 6, 'Cuidado Personal', 0, 13, 112, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (113, 6, 'Estomacales', 0, 13, 113, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (114, 6, 'Material de Curación', 0, 13, 114, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (115, 6, 'Incontinencia', 0, 13, 115, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (116, 6, 'Analgésicos', 0, 13, 116, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (117, 6, 'Bienestar Sexual', 0, 13, 117, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (118, 6, 'Medicamentos Genéricos', 0, 13, 118, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (119, 6, 'Medicamentos de Patente', 0, 13, 119, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (120, 6, 'Respiratorios', 0, 13, 120, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (121, 6, 'Oftálmicos y Oticos', 0, 13, 121, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (122, 6, 'Medicamentos de Alta Especialidad', 0, 13, 122, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (123, 6, 'Ortopedia y Equipos de Medición', 0, 13, 123, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (124, 6, 'Dieta', 0, 13, 124, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (125, 6, 'Naturistas y Herbolarios', 0, 13, 125, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (126, 6, 'Nutrición Deportiva', 0, 13, 126, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (127, 6, 'Cuidado de los Pies', 0, 13, 127, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (128, 6, 'Diabetes', 0, 13, 128, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (129, 6, 'Medicamentos Infantiles', 0, 13, 129, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (130, 6, 'Afeitado', 0, 14, 130, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (131, 6, 'Cuidado bucal', 0, 14, 131, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (132, 6, 'Cuidado Facial', 0, 14, 132, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (133, 6, 'Cosméticos', 0, 14, 133, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (134, 6, 'Cuidado del cabello', 0, 14, 134, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (135, 6, 'Higiene y cuidado corporal', 0, 14, 135, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (136, 6, 'Higiene y cuidado para manos', 0, 14, 136, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (137, 6, 'Cuidado para pies', 0, 14, 137, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (138, 6, 'Pañuelos desechables', 0, 14, 138, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (139, 6, 'Cuidado Íntimo', 0, 14, 139, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (140, 6, 'Kits de viaje', 0, 14, 140, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (141, 6, 'Higiene masculina', 0, 14, 141, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (142, 6, 'Desmaquillantes y quitaesmaltes', 0, 14, 142, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (143, 6, 'Productos destacados', 0, 14, 143, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (144, 6, 'Crema corporal y de manos', 0, 14, 144, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (145, 6, 'Televisores', 0, 15, 145, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (146, 6, 'Telefonía', 0, 15, 146, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (147, 6, 'Computación', 0, 15, 147, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (148, 6, 'Videojuegos', 0, 15, 148, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (149, 6, 'Audio', 0, 15, 149, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (150, 6, 'Fotografía', 0, 15, 150, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (151, 6, 'Accesorios para cocina', 0, 16, 151, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (152, 6, 'Accesorios para mesa', 0, 16, 152, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (153, 6, 'Artículos de temporada', 0, 16, 153, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (154, 6, 'Artículos deportivos', 0, 16, 154, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (155, 6, 'Colchones y Blancos', 0, 16, 155, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (156, 6, 'Decoración y Muebles', 0, 16, 156, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (157, 6, 'Ferretería y Pinturas', 0, 16, 157, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (158, 6, 'Jardineria y exteriores', 0, 16, 158, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (159, 6, 'Línea Blanca', 0, 16, 159, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (160, 6, 'Organización y Almacenamiento', 0, 16, 160, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (161, 6, 'Papelería', 0, 16, 161, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (162, 6, 'Electrodomésticos', 0, 16, 162, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (163, 6, 'Libros y Revistas', 0, 16, 163, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (164, 6, 'Autos y Motos', 0, 16, 164, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (165, 6, 'Ropa para Hombre', 0, 17, 165, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (166, 6, 'Ropa para Mujer', 0, 17, 166, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (167, 6, 'Ropa para Niña y Juvenil', 0, 17, 167, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (168, 6, 'Ropa para Niño y Juvenil', 0, 17, 168, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (169, 6, 'Zapatería', 0, 17, 169, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (170, 6, 'Ropa para Bebé', 0, 17, 170, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (171, 6, 'Juguetes para bebé y estimulación temprana', 0, 18, 171, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (172, 6, 'Muñecas y Accesorios', 0, 18, 172, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (173, 6, 'Figuras de Acción', 0, 18, 173, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (174, 6, 'Juegos de Mesa y Rompecabezas', 0, 18, 174, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (175, 6, 'Peluches y Electrónicos', 0, 18, 175, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (176, 6, 'Lanzadores', 0, 18, 176, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (177, 6, 'Triciclos y Montables', 0, 18, 177, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (178, 6, 'Aparatos de Ejercicio y Fitness', 0, 18, 178, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (179, 6, 'Campismo', 0, 18, 179, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (180, 6, 'Deportes Acuáticos', 0, 18, 180, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (181, 6, 'Deportes Individuales y en Equipo', 0, 18, 181, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (182, 6, 'Juegos Recreativos', 0, 18, 182, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (183, 6, 'Bicicletas', 0, 18, 183, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (184, 6, 'Juegos para Exterior y Albercas', 0, 18, 184, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (185, 6, 'Juegos de Ciencia y Creatividad', 0, 18, 185, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (186, 6, 'Vehículos y Autopistas', 0, 18, 186, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (187, 6, 'Juguetes de Construcción', 0, 18, 187, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 8, 'Abierto', 0, 0, 1, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 8, 'Pagado', 0, 0, 2, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (3, 8, 'Cancelado', 0, 3, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (1, 9, 'Normal', 0, 0, 1, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       (2, 9, 'En Línea', 0, 0, 2, 0, 0, GETUTCDATE(), 0, null, null, null, null);

-- 6. Catálogo de tiendas.
--------------------------
INSERT INTO [dbo].[mtStores] ([name], [address], [number_phone], [postal_code], [country_code], [federal_entity_code], [municipality_code],
                              [neighborhood_code], [issystemrow], [isdeleted], [creationdate], [account_id_creationdate],
                              [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
VALUES ('Centro de Distribución', 'Av. Siempreviva 101.', '5512345678', 0, 0, 0, 0, 0, 1, 0, GETUTCDATE(), 0, null, null, null, null);
       --('Sucursal CDMX', 'Av. Siempreviva 101.', '5512345678', 0, 0, 0, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       --('Sucursal Guadalajara', 'Av. Siempreviva 102.', '5512345678', 0, 0, 0, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       --('Sucursal Monterrey', 'Av. Siempreviva 103.', '5512345678', 0, 0, 0, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null),
       --('Sucursal Puebla', 'Av. Siempreviva 103.', '5512345678', 0, 0, 0, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null);

-- 7. Catálogo de proveedores.
------------------------------
INSERT INTO [dbo].[mtSuppliers] ([name], [address], [email], [number_phone], [postal_code], [country_code],  [federal_entity_code], [municipality_code],
                                 [neighborhood_code], [issystemrow], [isdeleted], [creationdate], [account_id_creationdate],
                                 [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
     VALUES ('Proveedor genérico', 'Sin domicilio', 'mailsupplier@mail.com', '5512345678', 0, 0, 0, 0, 0, 1, 0, GETUTCDATE(), 0, null, null, null, null);

-- 8. Catálogo de marcas asociadas a un proveedor.
--------------------------------------------------
INSERT INTO [dbo].[mtBrands] ([name], [supplier_id],
                              [issystemrow], [isdeleted], [creationdate], [account_id_creationdate],
                              [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
     VALUES ('Marca genérica', 0, 1, 0, GETUTCDATE(), 0, null, null, null, null);

-- 9. Catálogo de artículos.
----------------------------
--INSERT INTO [dbo].[mtArticles] ([short_name], [description], [total_in_vault],
--                                [purchase_price], [sale_price], [departament_id],
--                                [producttype_id], [supplier_id], [brand_id], [image_article],
--                                [issystemrow], [isdeleted], [creationdate], [account_id_creationdate],
--                                [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
--VALUES ('Bolsa de churros Neto', 'Bolsa de churros 100 grs', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Paquetaxo Morado Grande', 'Paquetaxo picoso ultrahot', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Paquetaxo Azul Grande', 'Paquetaxo sabor queso', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Paquetaxo Amarillo Grande', 'Paquetaxo botanero normal.', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Paquetaxo Verde Grande', 'Paquetaxo botanero extremo', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Cerveza Corona Chica', 'Cerveza 350 ml', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Cerveza Indio Chica', 'Cerveza 350 ml', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Cerveza Victoria Chica', 'Cerveza 350 ml', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Cerveza Corona Grande', 'Cerveza Cahuama 850 ml', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null),
--       ('Coca Cola Grande', 'Coca Cola Sabor Original 3 L', 0, 12.50, 12.50, 1, 28, 0, 0, null, 0, 0, GETUTCDATE(), 0, null, null, null, null);

-- 10. Catálogo de clientes.
----------------------------
INSERT INTO [dbo].[mtCustomers] ([first_name], [last_name], [address], [email], [curp_code], [rfc_code], [number_phone], [postal_code], [country_code],
                                 [federal_entity_code], [municipality_code], [neighborhood_code], [issystemrow], [isdeleted], 
																 [creationdate], [account_id_creationdate], [updatedate], [account_id_updatedate], [deletedate], [account_id_deletedate])
     VALUES ('CLIENTE', 'ESTÁNDAR', 'SIN DOMICILIO #0', 'mail1@mail.com', '', '', '', 0, 0, 0, 0, 0, 0, 0, GETUTCDATE(), 0, null, null, null, null);


-- 11. Agregamos las llaves foraneas de la tabla de usuarios, clientes, proveedores y sucursales.
-------------------------------------------------------------
ALTER TABLE [dbo].[mtUsers] ADD CONSTRAINT fk_IdUser1 FOREIGN KEY ([country_code]) REFERENCES mtCountries([country_code]);
ALTER TABLE [dbo].[mtStores] ADD CONSTRAINT fk_IdStore2 FOREIGN KEY ([country_code]) REFERENCES mtCountries([country_code]);
ALTER TABLE [dbo].[mtSuppliers] ADD CONSTRAINT fk_IdSupplier2 FOREIGN KEY ([country_code]) REFERENCES mtCountries([country_code]);
ALTER TABLE [dbo].[mtCustomers] ADD CONSTRAINT fk_IdCustomer2 FOREIGN KEY ([country_code]) REFERENCES mtCountries([country_code]);

-- DBCC CHECKIDENT ('mtArticles');
-- GO
-- 1633588490-LoadTables.sql

